[package]
name = "ai_template"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "*"
fastrand = "*"
once_cell = "*"

winit = "*"
vulkano = "0.34.0"
vulkano-win = "0.34.0"
vulkano-util = "0.34.0"
vulkano-macros = "0.34.0"
vulkano-shaders = "0.34.0"

[profile.dev]
opt-level = 1